[main]
include=throughput-performance

[cpu]
governor=powersave
min_perf_pct=20
energy_performance_preference=performance
energy_perf_bias=performance
boost=1

[script]
script=${i:PROFILE_DIR}/throttled-profile.sh
